### ISSUE TITLE
SpeedupWebMvcAutoConfiguration注解配置项不兼容springboot2.x

### ISSUE THREAD

**Issue by lplpysys** [alibaba/velocity-spring-boot-project#3]
添加velocity-spring-boot-starter 1.0.4以后，应用启动时报错。
报错信息：Error creating bean with name 'com.alibaba.boot.web.autoconfigure.SpeedupWebMvcAutoConfiguration'

错误详情：java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

原因初步分析：stackOverFlow上看分析是因为SpeedupWebMvcAutoConfiguration里的有些配置不兼容spring-boot 2.x

**Comment by mercyblitz** [comment]
请使用 1.0.4.RELEASE，本人测试了 1.5 到 2.2，均未发现问题
